name: C++ CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout repo
      uses: actions/checkout@v3

    - name: 🧰 Install build tools
      run: sudo apt-get install build-essential -y

    - name: 🏗️ Compile C++ project
      run: g++ -o wallet main.cpp src/*.cpp -Iinclude

    - name: ✅ Run (optional) test
      run: ./wallet < test_inputs.txt

  scan-security:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: 🧾 Checkout repo
      uses: actions/checkout@v3

    - name: 🔍 Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: 🚨 Trivy vulnerability scan
      run: trivy fs .

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: 🐳 Build Docker image
      run: docker build -t wallet-app .

    # Optional: Push to Docker Hub
    # - name: Login DockerHub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Push Docker image
    #   run: docker push your-dockerhub-username/wallet-app
